#!/usr/bin/bash 

file_path="$HOME/Media/Random/bm3/bm3_data.txt"

delete_entry() {
    selected_line=$(cat "$file_path" | sed '1!G;h;$!d' | rofi -dmenu -p "select information to delete" -width 60 -location 0)
    [ -n "$selected_line" ] && sed -i "/$(echo "$selected_line" | sed 's/[\/&]/\\&/g')/d" "$file_path"
}

save_info() {
    echo "$(date '+%Y-%m-%d %H:%M:%S'): $1" >> "$file_path"
}

select_info() {
    selected_line=$(cat "$file_path" | sed '1!G;h;$!d' | sed 's/^.\{21\}//' | rofi -dmenu "select information")
    
    [ -n "$selected_line" ] && entry=$(echo -n "$selected_line") && echo "$selected_line" | grep "https://" && { 
        choice=$(echo -e "Yes\nNo" | rofi -dmenu -p "do you want to open in browser?" -i)
        case $choice in
            "Yes") firefox "$entry" && exit 0 ;;
            "No") echo -n "$entry" | xclip -selection clipboard ;;
        esac
    } || { 
        echo -n "$entry" | xclip -selection clipboard 
        test $(echo "$entry" | wc -c) -gt 20 && rofi  -e "$entry"
    }
}

options=("show (x)" "save (b)" "delete (d)")

selected_option=$(printf "%s\n" "${options[@]}" | rofi -dmenu -p "select an option" )

case $selected_option in
    "save (b)")
        new_info=$(rofi -dmenu -p "enter information to save" )  
        [ -n "$new_info" ] && save_info "$new_info"
        ;;
    "show (x)")
        select_info
        ;;
    "delete (d)")
        delete_entry
        ;;
esac
