#!/bin/fish

function eo
    if test (count $argv) -eq 1
        set device $argv[1]
    
        set lol (basename $device)
    
        if not test -e /mnt/$lol
            sudo mkdir /mnt/$lol
        end
    
        if sudo st -e cryptsetup luksOpen /dev/$device $lol; and sudo mount /dev/mapper/$lol /mnt/$lol
            notify-send "[eo] mounted at /mnt/$lol"
        else
            sudo mount /dev/$lol /mnt/$lol
            notify-send "[eo] mounted at /mnt/$lol"
        end
    end
end

function ec
    if test (count $argv) -eq 1
        set device $argv[1]

        set lol (basename $device)

        if sudo umount /dev/mapper/$lol; and sudo cryptsetup luksClose $lol
            notify-send "[ec] unmounted"
        else
            sudo umount /dev/$lol
            notify-send "[ec] unmounted"
        end
    end

    sync
end

set device $(lsblk -l | sed 1d | grep -v -e nvme -e boot -e root | rofi -dmenu | awk '{print $1}')

set mountpoint $(lsblk -l | awk '{print $7}' | grep "$device")

if test -z "$mountpoint"
    eo "$device"
else
    ec "$device"
end
