#!/bin/bash 

function grep_search () {
    dictionary="/home/clyde/Media/Random/PDF and Books/Oxford English Dictionary.txt"
        
        if [ -n "$dictionary" ]; then
            file_path="$dictionary"
            
            file_content=$(grep -v '^$' "$file_path" | rofi -matching regex -dmenu -i -p "Search in dictionary" -mesg "")
            
            if [ -n "$file_content" ]; then
                rofi -e "$file_content"
        
                echo -n "$file_content" | xclip -selection clipboard
            fi
        fi
}

function query_search () {
    query=$(rofi -dmenu -i -p "Search in dictionary" -show-icons -lines 0 -no-fixed-num-lines)
    
    results=$(grep --color=auto -i "^$query" "/home/clyde/Media/Random/PDF and Books/Oxford English Dictionary.txt" | head -n 4 | sed G)
    
    if [ -n "$query" ]; then
        rofi -e "$results"
    fi
}

function oxf_online_search () {
    word=$(rofi -dmenu -p "enter the word to search online")
    
    firefox "https://www.oxfordlearnersdictionaries.com/definition/english/${word}_1?q=${word}"
}

function rae_online_search () {
    word=$(rofi -dmenu -p "ingresa la palabra para buscar en línea")
    
    firefox "https://dle.rae.es/${word}"
}

choice=$(echo -e "local query search\nlocal grep search\noxf online search\nrae online search" | rofi -dmenu)

case "$choice" in
  "local grep search")
    grep_search
    ;;
    "local query search")
    query_search
    ;;
    "oxf online search")
    oxf_online_search
    ;;
    "rae online search")
    rae_online_search
    ;;
esac
    



