#!/usr/bin/bash 

function grep_search () {
    dictionary="$HOME/media/random/PDF and Books/Oxford English Dictionary.txt"
        
        if [ -n "$dictionary" ]; then
            file_path="$dictionary"
            
            file_content=$(grep -v '^$' "$file_path" | rofi -matching regex -dmenu -i -p "Search in dictionary" -mesg "")
            
            if [ -n "$file_content" ]; then
                rofi -e "$file_content"
        
                echo -n "$file_content" | xclip -selection clipboard
            fi
        fi
}

function query_search () {
    query=$(rofi -dmenu -i -p "Search in dictionary" -show-icons -lines 0 -no-fixed-num-lines)
    
    results=$(grep --color=auto -i "^$query" "$HOME/media/random/PDF and Books/Oxford English Dictionary.txt" | head -n 4 | sed G)
    
    if [ -n "$query" ]; then
        rofi -e "$results"
        echo "$results" | xclip -sel c
    fi
}

function oxf_online_search () {
    word=$(rofi -dmenu -p "enter the word to search online")
    test -z $word && exit 1
    
    firefox "https://www.oxfordlearnersdictionaries.com/definition/english/${word}_1?q=${word}"
}

function rae_online_search () {
    word=$(rofi -dmenu -p "ingresa la palabra para buscar en línea")
    test -z $word && exit 1
    
    firefox "https://dle.rae.es/${word}"
}

function wiktionary () {
    word=$(rofi -dmenu -p "ingresa la palabra para buscar en línea")
    test -z $word && exit 1
    
    firefox "https://es.wiktionary.org/wiki/${word}"
}

choice=$(echo -e " local query\n oxf online\n rae online\n wiktionary\nGREP" | rofi -dmenu -theme-str 'window {width: 8%;}'  -dmenu -p "(")

case "$choice" in
    " local query")query_search;;
    " oxf online")oxf_online_search;;
    " rae online")rae_online_search;;
    " wiktionary")wiktionary;;
    "GREP")grep_search;;
esac
