#!/usr/bin/bash

emoji="😀 grinning face 
😃 grinning face with big eyes 
😄 grinning face with smiling eyes 
😁 beaming face with smiling eyes 
😆 grinning squinting face 
😅 grinning face with sweat 
🤣 rolling on the floor laughing 
😂 face with tears of joy 
🙂 slightly smiling face 
🙃 upside-down face 
🫠 melting face 
😉 winking face 
😊 smiling face with smiling eyes 
😇 smiling face with halo 
🥰 smiling face with hearts 
😍 smiling face with heart-eyes 
🤩 star-struck 
😘 face blowing a kiss 
😗 kissing face 
☺️ smiling face 
😚 kissing face with closed eyes 
😙 kissing face with smiling eyes 
🥲 smiling face with tear 
😋 face savoring food 
😛 face with tongue 
😜 winking face with tongue 
🤪 zany face 
😝 squinting face with tongue 
🤑 money-mouth face 
🤗 smiling face with open hands 
🤭 face with hand over mouth 
🫢 face with open eyes and hand over mouth 
🫣 face with peeking eye 
🤫 shushing face 
🤔 thinking face 
🫡 saluting face 
🤐 zipper-mouth face 
🤨 face with raised eyebrow 
😐 neutral face 
😑 expressionless face 
😶 face without mouth 
🫥 dotted line face 
😏 smirking face 
😒 unamused face 
🙄 face with rolling eyes 
😬 grimacing face 
🤥 lying face 
😌 relieved face 
😔 pensive face 
😪 sleepy face 
🤤 drooling face 
😴 sleeping face 
😷 face with medical mask 
🤒 face with thermometer 
🤕 face with head-bandage 
🤢 nauseated face 
🤮 face vomiting 
🤧 sneezing face 
🥵 hot face 
🥶 cold face 
🥴 woozy face 
😵 face with crossed-out eyes 
🤯 exploding head 
🤠 cowboy hat face 
🥳 partying face 
🥸 disguised face 
😎 smiling face with sunglasses 
🤓 nerd face 
🧐 face with monocle 
😕 confused face 
🫤 face with diagonal mouth 
😟 worried face 
🙁 slightly frowning face 
☹️ frowning face 
😮 face with open mouth 
😯 hushed face 
😲 astonished face 
😳 flushed face 
🥺 pleading face 
🥹 face holding back tears 
😦 frowning face with open mouth 
😧 anguished face 
😨 fearful face 
😰 anxious face with sweat 
😥 sad but relieved face 
😢 crying face 
😭 loudly crying face 
😱 face screaming in fear 
😖 confounded face 
😣 persevering face 
😞 disappointed face 
😓 downcast face with sweat 
😩 weary face 
😫 tired face 
🥱 yawning face 
😤 face with steam from nose 
😡 pouting face 
😠 angry face 
🤬 face with symbols on mouth 
😈 smiling face with horns 
👿 angry face with horns 
💀 skull 
☠️ skull and crossbones 
💩 pile of poo 
🤡 clown face 
👹 ogre 
👺 goblin 
👻 ghost 
👽 alien 
👾 alien monster 
🤖 robot 
😺 grinning cat 
😸 grinning cat with smiling eyes 
😹 cat with tears of joy 
😻 smiling cat with heart-eyes 
😼 cat with wry smile 
😽 kissing cat 
🙀 weary cat 
😿 crying cat 
😾 pouting cat 
🙈 see-no-evil monkey 
🙉 hear-no-evil monkey 
🙊 speak-no-evil monkey 
💋 kiss mark 
💌 love letter 
💘 heart with arrow 
💝 heart with ribbon 
💖 sparkling heart 
💗 growing heart 
💓 beating heart 
💞 revolving hearts 
💕 two hearts 
💟 heart decoration 
❣️ heart exclamation 
💔 broken heart 
❤️ red heart 
🧡 orange heart 
💛 yellow heart 
💚 green heart 
💙 blue heart 
💜 purple heart 
🤎 brown heart 
🖤 black heart 
🤍 white heart 
💯 hundred points 
💢 anger symbol 
💥 collision 
💫 dizzy 
💦 sweat droplets 
💨 dashing away 
🕳️ hole 
💣 bomb 
💬 speech balloon 
🗨️ left speech bubble 
🗯️ right anger bubble 
💭 thought balloon 
💤 zzz 
👋 waving hand 
🤚 raised back of hand 
🖐️ hand with fingers splayed 
✋ raised hand 
🖖 vulcan salute 
🫱 rightwards hand 
🫲 leftwards hand 
🫳 palm down hand 
🫴 palm up hand 
👌 OK hand 
🤌 pinched fingers 
🤏 pinching hand 
✌️ victory hand 
🤞 crossed fingers 
🫰 hand with index finger and thumb crossed 
🤟 love-you gesture 
🤘 sign of the horns 
🤙 call me hand 
👈 backhand index pointing left 
👉 backhand index pointing right 
👆 backhand index pointing up 
🖕 middle finger 
👇 backhand index pointing down 
☝️ index pointing up 
🫵 index pointing at the viewer 
👍 thumbs up 
👎 thumbs down 
✊ raised fist 
👊 oncoming fist 
🤛 left-facing fist 
🤜 right-facing fist 
👏 clapping hands 
🙌 raising hands 
🫶 heart hands 
👐 open hands 
🤲 palms up together 
🤝 handshake 
🙏 folded hands 
✍️ writing hand 
💅 nail polish 
🤳 selfie 
💪 flexed biceps 
🦾 mechanical arm 
🦿 mechanical leg 
🦵 leg 
🦶 foot 
👂 ear 
🦻 ear with hearing aid 
👃 nose 
🧠 brain 
🫀 anatomical heart 
🫁 lungs 
🦷 tooth 
🦴 bone 
👀 eyes 
👁️ eye 
👅 tongue 
👄 mouth 
🫦 biting lip 
👶 baby 
🧒 child 
👦 boy 
👧 girl 
🧑 person 
👱 person: blond hair 
👨 man 
🧔 person: beard 
👩 woman 
🧓 older person 
👴 old man 
👵 old woman 
🙍 person frowning 
🙎 person pouting 
🙅 person gesturing NO 
🙆 person gesturing OK 
💁 person tipping hand 
🙋 person raising hand 
🧏 deaf person 
🙇 person bowing 
🤦 person facepalming 
🤷 person shrugging 
👮 police officer 
🕵️ detective 
💂 guard 
🥷 ninja 
👷 construction worker 
🫅 person with crown 
🤴 prince 
👸 princess 
👳 person wearing turban 
👲 person with skullcap 
🧕 woman with headscarf 
🤵 person in tuxedo 
👰 person with veil 
🤰 pregnant woman 
🫃 pregnant man 
🫄 pregnant person 
🤱 breast-feeding 
👼 baby angel 
🎅 Santa Claus 
🤶 Mrs. Claus 
🦸 superhero 
🦹 supervillain 
🧙 mage 
🧚 fairy 
🧛 vampire 
🧜 merperson 
🧝 elf 
🧞 genie 
🧟 zombie 
🧌 troll 
💆 person getting massage 
💇 person getting haircut 
🚶 person walking 
🧍 person standing 
🧎 person kneeling 
🏃 person running 
💃 woman dancing 
🕺 man dancing 
🕴️ person in suit levitating 
👯 people with bunny ears 
🧖 person in steamy room 
🧗 person climbing 
🤺 person fencing 
🏇 horse racing 
⛷️ skier 
🏂 snowboarder 
🏌️ person golfing 
🏄 person surfing 
🚣 person rowing boat 
🏊 person swimming 
⛹️ person bouncing ball 
🏋️ person lifting weights 
🚴 person biking 
🚵 person mountain biking 
🤸 person cartwheeling 
🤼 people wrestling 
🤽 person playing water polo 
🤾 person playing handball 
🤹 person juggling 
🧘 person in lotus position 
🛀 person taking bath 
🛌 person in bed 
👭 women holding hands 
👫 woman and man holding hands 
👬 men holding hands 
💏 kiss 
💑 couple with heart 
👪 family 
🗣️ speaking head 
👤 bust in silhouette 
👥 busts in silhouette 
🫂 people hugging 
👣 footprints 
🐵 monkey face  (animal)
🐒 monkey  (animal)
🦍 gorilla  (animal)
🦧 orangutan  (animal)
🐶 dog face  (animal)
🐕 dog  (animal)
🦮 guide dog  (animal)
🐩 poodle  (animal)
🐺 wolf  (animal)
🦊 fox  (animal)
🦝 raccoon  (animal)
🐱 cat face  (animal)
🐈 cat  (animal)
🦁 lion  (animal)
🐯 tiger face  (animal)
🐅 tiger  (animal)
🐆 leopard  (animal)
🐴 horse face  (animal)
🐎 horse  (animal)
🦄 unicorn  (animal)
🦓 zebra  (animal)
🦌 deer  (animal)
🦬 bison  (animal)
🐮 cow face  (animal)
🐂 ox  (animal)
🐃 water buffalo  (animal)
🐄 cow  (animal)
🐷 pig face  (animal)
🐖 pig  (animal)
🐗 boar  (animal)
🐽 pig nose  (animal)
🐏 ram  (animal)
🐑 ewe  (animal)
🐐 goat  (animal)
🐪 camel  (animal)
🐫 two-hump camel  (animal)
🦙 llama  (animal)
🦒 giraffe  (animal)
🐘 elephant  (animal)
🦣 mammoth  (animal)
🦏 rhinoceros  (animal)
🦛 hippopotamus  (animal)
🐭 mouse face  (animal)
🐁 mouse  (animal)
🐀 rat  (animal)
🐹 hamster  (animal)
🐰 rabbit face  (animal)
🐇 rabbit  (animal)
🐿️ chipmunk  (animal)
🦫 beaver  (animal)
🦔 hedgehog  (animal)
🦇 bat  (animal)
🐻 bear  (animal)
🐨 koala  (animal)
🐼 panda  (animal)
🦥 sloth  (animal)
🦦 otter  (animal)
🦨 skunk  (animal)
🦘 kangaroo  (animal)
🦡 badger  (animal)
🐾 paw prints  (animal)
🦃 turkey  (animal)
🐔 chicken  (animal)
🐓 rooster  (animal)
🐣 hatching chick  (animal)
🐤 baby chick  (animal)
🐥 front-facing baby chick  (animal)
🐦 bird  (animal)
🐧 penguin  (animal)
🕊️ dove  (animal)
🦅 eagle  (animal)
🦆 duck  (animal)
🦢 swan  (animal)
🦉 owl  (animal)
🦤 dodo  (animal)
🪶 feather  (animal)
🦩 flamingo  (animal)
🦚 peacock  (animal)
🦜 parrot  (animal)
🐸 frog  (animal)
🐊 crocodile  (animal)
🐢 turtle  (animal)
🦎 lizard  (animal)
🐍 snake  (animal)
🐲 dragon face  (animal)
🐉 dragon  (animal)
🦕 sauropod  (animal)
🦖 T-Rex  (animal)
🐳 spouting whale  (animal)
🐋 whale  (animal)
🐬 dolphin  (animal)
🦭 seal  (animal)
🐟 fish  (animal)
🐠 tropical fish  (animal)
🐡 blowfish  (animal)
🦈 shark  (animal)
🐙 octopus  (animal)
🐚 spiral shell  (animal)
🪸 coral  (animal)
🐌 snail  (animal)
🦋 butterfly  (animal)
🐛 bug  (animal)
🐜 ant  (animal)
🐝 honeybee  (animal)
🪲 beetle  (animal)
🐞 lady beetle  (animal)
🦗 cricket  (animal)
🪳 cockroach  (animal)
🕷️ spider  (animal)
🕸️ spider web  (animal)
🦂 scorpion  (animal)
🦟 mosquito  (animal)
🪰 fly  (animal)
🪱 worm  (animal)
🦠 microbe  (nature)
💐 bouquet  (nature)
🌸 cherry blossom  (nature)
💮 white flower  (nature)
🪷 lotus  (nature)
🏵️ rosette  (nature)
🌹 rose  (nature)
🥀 wilted flower  (nature)
🌺 hibiscus  (nature)
🌻 sunflower  (nature)
🌼 blossom  (nature)
🌷 tulip  (nature)
🌱 seedling  (nature)
🪴 potted plant  (nature)
🌲 evergreen tree  (nature)
🌳 deciduous tree  (nature)
🌴 palm tree  (nature)
🌵 cactus  (nature)
🌾 sheaf of rice  (nature)
🌿 herb  (nature)
☘️ shamrock  (nature)
🍀 four leaf clover  (nature)
🍁 maple leaf  (nature)
🍂 fallen leaf  (nature)
🍃 leaf fluttering in wind  (nature)
🪹 empty nest  (nature)
🪺 nest with eggs  (nature)
🍇 grapes  (food)
🍈 melon  (food)
🍉 watermelon  (food)
🍊 tangerine  (food)
🍋 lemon  (food)
🍌 banana  (food)
🍍 pineapple  (food)
🥭 mango  (food)
🍎 red apple  (food)
🍏 green apple  (food)
🍐 pear  (food)
🍑 peach  (food)
🍒 cherries  (food)
🍓 strawberry  (food)
🫐 blueberries  (food)
🥝 kiwi fruit  (food)
🍅 tomato  (food)
🫒 olive  (food)
🥥 coconut  (food)
🥑 avocado  (food)
🍆 eggplant  (food)
🥔 potato  (food)
🥕 carrot  (food)
🌽 ear of corn  (food)
🌶️ hot pepper  (food)
🫑 bell pepper  (food)
🥒 cucumber  (food)
🥬 leafy green  (food)
🥦 broccoli  (food)
🧄 garlic  (food)
🧅 onion  (food)
🍄 mushroom  (food)
🥜 peanuts  (food)
🫘 beans  (food)
🌰 chestnut  (food)
🍞 bread  (food)
🥐 croissant  (food)
🥖 baguette bread  (food)
🫓 flatbread  (food)
🥨 pretzel  (food)
🥯 bagel  (food)
🥞 pancakes  (food)
🧇 waffle  (food)
🧀 cheese wedge  (food)
🍖 meat on bone  (food)
🍗 poultry leg  (food)
🥩 cut of meat  (food)
🥓 bacon  (food)
🍔 hamburger  (food)
🍟 french fries  (food)
🍕 pizza  (food)
🌭 hot dog  (food)
🥪 sandwich  (food)
🌮 taco  (food)
🌯 burrito  (food)
🫔 tamale  (food)
🥙 stuffed flatbread  (food)
🧆 falafel  (food)
🥚 egg  (food)
🍳 cooking  (food)
🥘 shallow pan of food  (food)
🍲 pot of food  (food)
🫕 fondue  (food)
🥣 bowl with spoon  (food)
🥗 green salad  (food)
🍿 popcorn  (food)
🧈 butter  (food)
🧂 salt  (food)
🥫 canned food  (food)
🍱 bento box  (food)
🍘 rice cracker  (food)
🍙 rice ball  (food)
🍚 cooked rice  (food)
🍛 curry rice  (food)
🍜 steaming bowl  (food)
🍝 spaghetti  (food)
🍠 roasted sweet potato  (food)
🍢 oden  (food)
🍣 sushi  (food)
🍤 fried shrimp  (food)
🍥 fish cake with swirl  (food)
🥮 moon cake  (food)
🍡 dango  (food)
🥟 dumpling  (food)
🥠 fortune cookie  (food)
🥡 takeout box  (food)
🦀 crab  (food)
🦞 lobster  (food)
🦐 shrimp  (food)
🦑 squid  (food)
🦪 oyster  (food)
🍦 soft ice cream  (food)
🍧 shaved ice  (food)
🍨 ice cream  (food)
🍩 doughnut  (food)
🍪 cookie  (food)
🎂 birthday cake  (food)
🍰 shortcake  (food)
🧁 cupcake  (food)
🥧 pie  (food)
🍫 chocolate bar  (food)
🍬 candy  (food)
🍭 lollipop  (food)
🍮 custard  (food)
🍯 honey pot  (food)
🍼 baby bottle  (food)
🥛 glass of milk  (food)
☕ hot beverage  (food)
🫖 teapot  (food)
🍵 teacup without handle  (food)
🍶 sake  (food)
🍾 bottle with popping cork  (food)
🍷 wine glass  (food)
🍸 cocktail glass  (food)
🍹 tropical drink  (food)
🍺 beer mug  (food)
🍻 clinking beer mugs  (food)
🥂 clinking glasses  (food)
🥃 tumbler glass  (food)
🫗 pouring liquid  (food)
🥤 cup with straw  (food)
🧋 bubble tea  (food)
🧃 beverage box  (food)
🧉 mate  (food)
🧊 ice 
🥢 chopsticks 
🍽️ fork and knife with plate 
🍴 fork and knife 
🥄 spoon 
🔪 kitchen knife 
🫙 jar 
🏺 amphora 
🌍 globe showing Europe-Africa 
🌎 globe showing Americas 
🌏 globe showing Asia-Australia 
🌐 globe with meridians 
🗺️ world map 
🗾 map of Japan 
🧭 compass 
🏔️ snow-capped mountain 
⛰️ mountain 
🌋 volcano 
🗻 mount fuji 
🏕️ camping 
🏖️ beach with umbrella 
🏜️ desert 
🏝️ desert island 
🏞️ national park 
🏟️ stadium 
🏛️ classical building 
🏗️ building construction 
🧱 brick 
🪨 rock 
🪵 wood 
🛖 hut 
🏘️ houses 
🏚️ derelict house 
🏠 house 
🏡 house with garden 
🏢 office building 
🏣 Japanese post office 
🏤 post office 
🏥 hospital 
🏦 bank 
🏨 hotel 
🏩 love hotel 
🏪 convenience store 
🏫 school 
🏬 department store 
🏭 factory 
🏯 Japanese castle 
🏰 castle 
💒 wedding 
🗼 Tokyo tower 
🗽 Statue of Liberty 
⛪ church 
🕌 mosque 
🛕 hindu temple 
🕍 synagogue 
⛩️ shinto shrine 
🕋 kaaba 
⛲ fountain 
⛺ tent 
🌁 foggy 
🌃 night with stars 
🏙️ cityscape 
🌄 sunrise over mountains 
🌅 sunrise 
🌆 cityscape at dusk 
🌇 sunset 
🌉 bridge at night 
♨️ hot springs 
🎠 carousel horse 
🛝 playground slide 
🎡 ferris wheel 
🎢 roller coaster 
💈 barber pole 
🎪 circus tent 
🚂 locomotive 
🚃 railway car 
🚄 high-speed train 
🚅 bullet train 
🚆 train 
🚇 metro 
🚈 light rail 
🚉 station 
🚊 tram 
🚝 monorail 
🚞 mountain railway 
🚋 tram car 
🚌 bus 
🚍 oncoming bus 
🚎 trolleybus 
🚐 minibus 
🚑 ambulance 
🚒 fire engine 
🚓 police car 
🚔 oncoming police car 
🚕 taxi 
🚖 oncoming taxi 
🚗 automobile 
🚘 oncoming automobile 
🚙 sport utility vehicle 
🛻 pickup truck 
🚚 delivery truck 
🚛 articulated lorry 
🚜 tractor 
🏎️ racing car 
🏍️ motorcycle 
🛵 motor scooter 
🦽 manual wheelchair 
🦼 motorized wheelchair 
🛺 auto rickshaw 
🚲 bicycle 
🛴 kick scooter 
🛹 skateboard 
🛼 roller skate 
🚏 bus stop 
🛣️ motorway 
🛤️ railway track 
🛢️ oil drum 
⛽ fuel pump 
🛞 wheel 
🚨 police car light 
🚥 horizontal traffic light 
🚦 vertical traffic light 
🛑 stop sign 
🚧 construction 
⚓ anchor 
🛟 ring buoy 
⛵ sailboat 
🛶 canoe 
🚤 speedboat 
🛳️ passenger ship 
⛴️ ferry 
🛥️ motor boat 
🚢 ship 
✈️ airplane 
🛩️ small airplane 
🛫 airplane departure 
🛬 airplane arrival 
🪂 parachute 
💺 seat 
🚁 helicopter 
🚟 suspension railway 
🚠 mountain cableway 
🚡 aerial tramway 
🛰️ satellite 
🚀 rocket 
🛸 flying saucer 
🛎️ bellhop bell 
🧳 luggage 
⌛ hourglass done 
⏳ hourglass not done 
⌚ watch 
⏰ alarm clock 
⏱️ stopwatch 
⏲️ timer clock 
🕰️ mantelpiece clock 
🕛 twelve o’clock 
🕧 twelve-thirty 
🕐 one o’clock 
🕜 one-thirty 
🕑 two o’clock 
🕝 two-thirty 
🕒 three o’clock 
🕞 three-thirty 
🕓 four o’clock 
🕟 four-thirty 
🕔 five o’clock 
🕠 five-thirty 
🕕 six o’clock 
🕡 six-thirty 
🕖 seven o’clock 
🕢 seven-thirty 
🕗 eight o’clock 
🕣 eight-thirty 
🕘 nine o’clock 
🕤 nine-thirty 
🕙 ten o’clock 
🕥 ten-thirty 
🕚 eleven o’clock 
🕦 eleven-thirty 
🌑 new moon 
🌒 waxing crescent moon 
🌓 first quarter moon 
🌔 waxing gibbous moon 
🌕 full moon 
🌖 waning gibbous moon 
🌗 last quarter moon 
🌘 waning crescent moon 
🌙 crescent moon 
🌚 new moon face 
🌛 first quarter moon face 
🌜 last quarter moon face 
🌡️ thermometer 
☀️ sun 
🌝 full moon face 
🌞 sun with face 
🪐 ringed planet 
⭐ star 
🌟 glowing star 
🌠 shooting star 
🌌 milky way 
☁️ cloud 
⛅ sun behind cloud 
⛈️ cloud with lightning and rain 
🌤️ sun behind small cloud 
🌥️ sun behind large cloud 
🌦️ sun behind rain cloud 
🌧️ cloud with rain 
🌨️ cloud with snow 
🌩️ cloud with lightning 
🌪️ tornado 
🌫️ fog 
🌬️ wind face 
🌀 cyclone 
🌈 rainbow 
🌂 closed umbrella  (object)
☂️ umbrella  (object)
☔ umbrella with rain drops  (object)
⛱️ umbrella on ground  (object)
⚡ high voltage  (object)
❄️ snowflake  (object)
☃️ snowman  (object)
⛄ snowman without snow  (object)
☄️ comet  (object)
🔥 fire  (object)
💧 droplet  (object)
🌊 water wave  (object)
🎃 jack-o-lantern  (object)
🎄 Christmas tree  (object)
🎆 fireworks  (object)
🎇 sparkler  (object)
🧨 firecracker  (object)
✨ sparkles  (object)
🎈 balloon  (object)
🎉 party popper  (object)
🎊 confetti ball  (object)
🎋 tanabata tree  (object)
🎍 pine decoration  (object)
🎎 Japanese dolls  (object)
🎏 carp streamer  (object)
🎐 wind chime  (object)
🎑 moon viewing ceremony  (object)
🧧 red envelope  (object)
🎀 ribbon  (object)
🎁 wrapped gift  (object)
🎗️ reminder ribbon  (object)
🎟️ admission tickets  (object)
🎫 ticket  (object)
🎖️ military medal  (object)
🏆 trophy  (object)
🏅 sports medal  (object)
🥇 1st place medal  (object)
🥈 2nd place medal  (object)
🥉 3rd place medal  (object)
⚽ soccer ball  (object)
⚾ baseball  (object)
🥎 softball  (object)
🏀 basketball  (object)
🏐 volleyball  (object)
🏈 american football  (object)
🏉 rugby football  (object)
🎾 tennis  (object)
🥏 flying disc  (object)
🎳 bowling  (object)
🏏 cricket game  (object)
🏑 field hockey  (object)
🏒 ice hockey  (object)
🥍 lacrosse  (object)
🏓 ping pong  (object)
🏸 badminton  (object)
🥊 boxing glove  (object)
🥋 martial arts uniform  (object)
🥅 goal net  (object)
⛳ flag in hole  (object)
⛸️ ice skate  (object)
🎣 fishing pole  (object)
🤿 diving mask  (object)
🎽 running shirt  (object)
🎿 skis  (object)
🛷 sled  (object)
🥌 curling stone  (object)
🎯 bullseye  (object)
🪀 yo-yo  (object)
🪁 kite  (object)
🎱 pool 8 ball  (object)
🔮 crystal ball  (object)
🪄 magic wand  (object)
🧿 nazar amulet  (object)
🪬 hamsa  (object)
🎮 video game  (object)
🕹️ joystick  (object)
🎰 slot machine  (object)
🎲 game die  (object)
🧩 puzzle piece  (object)
🧸 teddy bear  (object)
🪅 piñata  (object)
🪩 mirror ball  (object)
🪆 nesting dolls  (object)
♠️ spade suit  (object)
♥️ heart suit  (object)
♦️ diamond suit  (object)
♣️ club suit  (object)
♟️ chess pawn  (object)
🃏 joker  (object)
🀄 mahjong red dragon  (object)
🎴 flower playing cards  (object)
🎭 performing arts  (object)
🖼️ framed picture  (object)
🎨 artist palette  (object)
🧵 thread  (object)
🪡 sewing needle  (object)
🧶 yarn  (object)
🪢 knot  (object)
👓 glasses  (object)
🕶️ sunglasses  (object)
🥽 goggles  (object)
🥼 lab coat  (object)
🦺 safety vest  (object)
👔 necktie  (object)
👕 t-shirt  (object)
👖 jeans  (object)
🧣 scarf  (object)
🧤 gloves  (object)
🧥 coat  (object)
🧦 socks  (object)
👗 dress  (object)
👘 kimono  (object)
🥻 sari  (object)
🩱 one-piece swimsuit  (object)
🩲 briefs  (object)
🩳 shorts  (object)
👙 bikini  (object)
👚 woman’s clothes  (object)
👛 purse  (object)
👜 handbag  (object)
👝 clutch bag  (object)
🛍️ shopping bags  (object)
🎒 backpack  (object)
🩴 thong sandal  (object)
👞 man’s shoe  (object)
👟 running shoe  (object)
🥾 hiking boot  (object)
🥿 flat shoe  (object)
👠 high-heeled shoe  (object)
👡 woman’s sandal  (object)
🩰 ballet shoes  (object)
👢 woman’s boot  (object)
👑 crown  (object)
👒 woman’s hat  (object)
🎩 top hat  (object)
🎓 graduation cap  (object)
🧢 billed cap  (object)
🪖 military helmet  (object)
⛑️ rescue worker’s helmet  (object)
📿 prayer beads  (object)
💄 lipstick  (object)
💍 ring  (object)
💎 gem stone  (object)
🔇 muted speaker  (object)
🔈 speaker low volume  (object)
🔉 speaker medium volume  (object)
🔊 speaker high volume  (object)
📢 loudspeaker  (object)
📣 megaphone  (object)
📯 postal horn  (object)
🔔 bell  (object)
🔕 bell with slash  (object)
🎼 musical score  (object)
🎵 musical note  (object)
🎶 musical notes  (object)
🎙️ studio microphone  (object)
🎚️ level slider  (object)
🎛️ control knobs  (object)
🎤 microphone  (object)
🎧 headphone  (object)
📻 radio  (object)
🎷 saxophone  (object)
🪗 accordion  (object)
🎸 guitar  (object)
🎹 musical keyboard  (object)
🎺 trumpet  (object)
🎻 violin  (object)
🪕 banjo  (object)
🥁 drum  (object)
🪘 long drum  (object)
📱 mobile phone  (object)
📲 mobile phone with arrow  (object)
☎️ telephone  (object)
📞 telephone receiver  (object)
📟 pager  (object)
📠 fax machine  (object)
🔋 battery  (object)
🪫 low battery  (object)
🔌 electric plug  (object)
💻 laptop  (object)
🖥️ desktop computer  (object)
🖨️ printer  (object)
⌨️ keyboard  (object)
🖱️ computer mouse  (object)
🖲️ trackball  (object)
💽 computer disk  (object)
💾 floppy disk  (object)
💿 optical disk  (object)
📀 dvd  (object)
🧮 abacus  (object)
🎥 movie camera  (object)
🎞️ film frames  (object)
📽️ film projector  (object)
🎬 clapper board  (object)
📺 television  (object)
📷 camera  (object)
📸 camera with flash  (object)
📹 video camera  (object)
📼 videocassette  (object)
🔍 magnifying glass tilted left  (object)
🔎 magnifying glass tilted right  (object)
🕯️ candle  (object)
💡 light bulb  (object)
🔦 flashlight  (object)
🏮 red paper lantern  (object)
🪔 diya lamp  (object)
📔 notebook with decorative cover  (object)
📕 closed book  (object)
📖 open book  (object)
📗 green book  (object)
📘 blue book  (object)
📙 orange book  (object)
📚 books  (object)
📓 notebook  (object)
📒 ledger  (object)
📃 page with curl  (object)
📜 scroll  (object)
📄 page facing up  (object)
📰 newspaper  (object)
🗞️ rolled-up newspaper  (object)
📑 bookmark tabs  (object)
🔖 bookmark  (object)
🏷️ label  (object)
💰 money bag  (object)
🪙 coin  (object)
💴 yen banknote  (object)
💵 dollar banknote  (object)
💶 euro banknote  (object)
💷 pound banknote  (object)
💸 money with wings  (object)
💳 credit card  (object)
🧾 receipt  (object)
💹 chart increasing with yen  (object)
✉️ envelope  (object)
📧 e-mail  (object)
📨 incoming envelope  (object)
📩 envelope with arrow  (object)
📤 outbox tray  (object)
📥 inbox tray  (object)
📦 package  (object)
📫 closed mailbox with raised flag  (object)
📪 closed mailbox with lowered flag  (object)
📬 open mailbox with raised flag  (object)
📭 open mailbox with lowered flag  (object)
📮 postbox  (object)
🗳️ ballot box with ballot  (object)
✏️ pencil  (object)
✒️ black nib  (object)
🖋️ fountain pen  (object)
🖊️ pen  (object)
🖌️ paintbrush  (object)
🖍️ crayon  (object)
📝 memo  (object)
💼 briefcase  (object)
📁 file folder  (object)
📂 open file folder  (object)
🗂️ card index dividers  (object)
📅 calendar  (object)
📆 tear-off calendar  (object)
🗒️ spiral notepad  (object)
🗓️ spiral calendar  (object)
📇 card index  (object)
📈 chart increasing  (object)
📉 chart decreasing  (object)
📊 bar chart  (object)
📋 clipboard  (object)
📌 pushpin  (object)
📍 round pushpin  (object)
📎 paperclip  (object)
🖇️ linked paperclips  (object)
📏 straight ruler  (object)
📐 triangular ruler  (object)
✂️ scissors  (object)
🗃️ card file box  (object)
🗄️ file cabinet  (object)
🗑️ wastebasket  (object)
🔒 locked  (object)
🔓 unlocked  (object)
🔏 locked with pen  (object)
🔐 locked with key  (object)
🔑 key  (object)
🗝️ old key  (object)
🔨 hammer  (object)
🪓 axe  (object)
⛏️ pick  (object)
⚒️ hammer and pick  (object)
🛠️ hammer and wrench  (object)
🗡️ dagger  (object)
⚔️ crossed swords  (object)
🔫 water pistol  (object)
🪃 boomerang  (object)
🏹 bow and arrow  (object)
🛡️ shield  (object)
🪚 carpentry saw  (object)
🔧 wrench  (object)
🪛 screwdriver  (object)
🔩 nut and bolt  (object)
⚙️ gear  (object)
🗜️ clamp  (object)
⚖️ balance scale  (object)
🦯 white cane  (object)
🔗 link  (object)
⛓️ chains  (object)
🪝 hook  (object)
🧰 toolbox  (object)
🧲 magnet  (object)
🪜 ladder  (object)
⚗️ alembic  (object)
🧪 test tube  (object)
🧫 petri dish  (object)
🧬 dna  (object)
🔬 microscope  (object)
🔭 telescope  (object)
📡 satellite antenna  (object)
💉 syringe  (object)
🩸 drop of blood  (object)
💊 pill  (object)
🩹 adhesive bandage  (object)
🩼 crutch  (object)
🩺 stethoscope  (object)
🩻 x-ray  (object)
🚪 door  (object)
🛗 elevator  (object)
🪞 mirror  (object)
🪟 window  (object)
🛏️ bed  (object)
🛋️ couch and lamp  (object)
🪑 chair  (object)
🚽 toilet  (object)
🪠 plunger  (object)
🚿 shower  (object)
🛁 bathtub  (object)
🪤 mouse trap  (object)
🪒 razor  (object)
🧴 lotion bottle  (object)
🧷 safety pin  (object)
🧹 broom  (object)
🧺 basket  (object)
🧻 roll of paper  (object)
🪣 bucket  (object)
🧼 soap  (object)
🫧 bubbles  (object)
🪥 toothbrush  (object)
🧽 sponge  (object)
🧯 fire extinguisher  (object)
🛒 shopping cart  (object)
🚬 cigarette  (object)
⚰️ coffin  (object)
🪦 headstone  (object)
⚱️ funeral urn  (object)
🗿 moai  (object)
🪧 placard  (object)
🪪 identification card  (object)
🏧 ATM sign 
🚮 litter in bin sign 
🚰 potable water 
♿ wheelchair symbol 
🚹 men’s room 
🚺 women’s room 
🚻 restroom 
🚼 baby symbol 
🚾 water closet 
🛂 passport control 
🛃 customs 
🛄 baggage claim 
🛅 left luggage 
⚠️ warning 
🚸 children crossing 
⛔ no entry 
🚫 prohibited 
🚳 no bicycles 
🚭 no smoking 
🚯 no littering 
🚱 non-potable water 
🚷 no pedestrians 
📵 no mobile phones 
🔞 no one under eighteen 
☢️ radioactive 
☣️ biohazard 
⬆️ up arrow 
↗️ up-right arrow 
➡️ right arrow 
↘️ down-right arrow 
⬇️ down arrow 
↙️ down-left arrow 
⬅️ left arrow 
↖️ up-left arrow 
↕️ up-down arrow 
↔️ left-right arrow 
↩️ right arrow curving left 
↪️ left arrow curving right 
⤴️ right arrow curving up 
⤵️ right arrow curving down 
🔃 clockwise vertical arrows 
🔄 counterclockwise arrows button 
🔙 BACK arrow 
🔚 END arrow 
🔛 ON! arrow 
🔜 SOON arrow 
🔝 TOP arrow 
🛐 place of worship 
⚛️ atom symbol 
🕉️ om 
✡️ star of David 
☸️ wheel of dharma 
☯️ yin yang 
✝️ latin cross 
☦️ orthodox cross 
☪️ star and crescent 
☮️ peace symbol 
🕎 menorah 
🔯 dotted six-pointed star 
♈ Aries 
♉ Taurus 
♊ Gemini 
♋ Cancer 
♌ Leo 
♍ Virgo 
♎ Libra 
♏ Scorpio 
♐ Sagittarius 
♑ Capricorn 
♒ Aquarius 
♓ Pisces 
⛎ Ophiuchus 
🔀 shuffle tracks button 
🔁 repeat button 
🔂 repeat single button 
▶️ play button 
⏩ fast-forward button 
⏭️ next track button 
⏯️ play or pause button 
◀️ reverse button 
⏪ fast reverse button 
⏮️ last track button 
🔼 upwards button 
⏫ fast up button 
🔽 downwards button 
⏬ fast down button 
⏸️ pause button 
⏹️ stop button 
⏺️ record button 
⏏️ eject button 
🎦 cinema 
🔅 dim button 
🔆 bright button 
📶 antenna bars 
📳 vibration mode 
📴 mobile phone off 
♀️ female sign 
♂️ male sign 
⚧️ transgender symbol 
✖️ multiply 
➕ plus 
➖ minus 
➗ divide 
🟰 heavy equals sign 
♾️ infinity 
‼️ double exclamation mark 
⁉️ exclamation question mark 
❓ red question mark 
❔ white question mark 
❕ white exclamation mark 
❗ red exclamation mark 
〰️ wavy dash 
💱 currency exchange 
💲 heavy dollar sign 
⚕️ medical symbol 
♻️ recycling symbol 
⚜️ fleur-de-lis 
🔱 trident emblem 
📛 name badge 
🔰 Japanese symbol for beginner 
⭕ hollow red circle 
✅ check mark button 
☑️ check box with check 
✔️ check mark 
❌ cross mark 
❎ cross mark button 
➰ curly loop 
➿ double curly loop 
〽️ part alternation mark 
✳️ eight-spoked asterisk 
✴️ eight-pointed star 
❇️ sparkle 
©️ copyright 
®️ registered 
™️ trade mark 
#️⃣ keycap: # 
*️⃣ keycap: * 
0️⃣ keycap: 0 
1️⃣ keycap: 1 
2️⃣ keycap: 2 
3️⃣ keycap: 3 
4️⃣ keycap: 4 
5️⃣ keycap: 5 
6️⃣ keycap: 6 
7️⃣ keycap: 7 
8️⃣ keycap: 8 
9️⃣ keycap: 9 
🔟 keycap: 10 
🔠 input latin uppercase 
🔡 input latin lowercase 
🔢 input numbers 
🔣 input symbols 
🔤 input latin letters 
🅰️ A button (blood type) 
🆎 AB button (blood type) 
🅱️ B button (blood type) 
🆑 CL button 
🆒 COOL button 
🆓 FREE button 
ℹ️ information 
🆔 ID button 
Ⓜ️ circled M 
🆕 NEW button 
🆖 NG button 
🅾️ O button (blood type) 
🆗 OK button 
🅿️ P button 
🆘 SOS button 
🆙 UP! button 
🆚 VS button 
🈁 Japanese “here” button 
🈂️ Japanese “service charge” button 
🈷️ Japanese “monthly amount” button 
🈶 Japanese “not free of charge” button 
🈯 Japanese “reserved” button 
🉐 Japanese “bargain” button 
🈹 Japanese “discount” button 
🈚 Japanese “free of charge” button 
🈲 Japanese “prohibited” button 
🉑 Japanese “acceptable” button 
🈸 Japanese “application” button 
🈴 Japanese “passing grade” button 
🈳 Japanese “vacancy” button 
㊗️ Japanese “congratulations” button 
㊙️ Japanese “secret” button 
🈺 Japanese “open for business” button 
🈵 Japanese “no vacancy” button 
🔴 red circle 
🟠 orange circle 
🟡 yellow circle 
🟢 green circle 
🔵 blue circle 
🟣 purple circle 
🟤 brown circle 
⚫ black circle 
⚪ white circle 
🟥 red square 
🟧 orange square 
🟨 yellow square 
🟩 green square 
🟦 blue square 
🟪 purple square 
🟫 brown square 
⬛ black large square 
⬜ white large square 
◼️ black medium square 
◻️ white medium square 
◾ black medium-small square 
◽ white medium-small square 
▪️ black small square 
▫️ white small square 
🔶 large orange diamond 
🔷 large blue diamond 
🔸 small orange diamond 
🔹 small blue diamond 
🔺 red triangle pointed up 
🔻 red triangle pointed down 
💠 diamond with a dot 
🔘 radio button 
🔳 white square button 
🔲 black square button 
🏁 chequered flag 
🚩 triangular flag 
🎌 crossed flags 
🏴 black flag 
🏳️ white flag 
🇦🇨 flag: Ascension Island 
🇦🇩 flag: Andorra 
🇦🇪 flag: United Arab Emirates 
🇦🇫 flag: Afghanistan 
🇦🇬 flag: Antigua & Barbuda 
🇦🇮 flag: Anguilla 
🇦🇱 flag: Albania 
🇦🇲 flag: Armenia 
🇦🇴 flag: Angola 
🇦🇶 flag: Antarctica 
🇦🇷 flag: Argentina 
🇦🇸 flag: American Samoa 
🇦🇹 flag: Austria 
🇦🇺 flag: Australia 
🇦🇼 flag: Aruba 
🇦🇽 flag: Åland Islands 
🇦🇿 flag: Azerbaijan 
🇧🇦 flag: Bosnia & Herzegovina 
🇧🇧 flag: Barbados 
🇧🇩 flag: Bangladesh 
🇧🇪 flag: Belgium 
🇧🇫 flag: Burkina Faso 
🇧🇬 flag: Bulgaria 
🇧🇭 flag: Bahrain 
🇧🇮 flag: Burundi 
🇧🇯 flag: Benin 
🇧🇱 flag: St. Barthélemy 
🇧🇲 flag: Bermuda 
🇧🇳 flag: Brunei 
🇧🇴 flag: Bolivia 
🇧🇶 flag: Caribbean Netherlands 
🇧🇷 flag: Brazil 
🇧🇸 flag: Bahamas 
🇧🇹 flag: Bhutan 
🇧🇻 flag: Bouvet Island 
🇧🇼 flag: Botswana 
🇧🇾 flag: Belarus 
🇧🇿 flag: Belize 
🇨🇦 flag: Canada 
🇨🇨 flag: Cocos (Keeling) Islands 
🇨🇩 flag: Congo - Kinshasa 
🇨🇫 flag: Central African Republic 
🇨🇬 flag: Congo - Brazzaville 
🇨🇭 flag: Switzerland 
🇨🇮 flag: Côte d’Ivoire 
🇨🇰 flag: Cook Islands 
🇨🇱 flag: Chile 
🇨🇲 flag: Cameroon 
🇨🇳 flag: China 
🇨🇴 flag: Colombia 
🇨🇵 flag: Clipperton Island 
🇨🇷 flag: Costa Rica 
🇨🇺 flag: Cuba 
🇨🇻 flag: Cape Verde 
🇨🇼 flag: Curaçao 
🇨🇽 flag: Christmas Island 
🇨🇾 flag: Cyprus 
🇨🇿 flag: Czechia 
🇩🇪 flag: Germany 
🇩🇬 flag: Diego Garcia 
🇩🇯 flag: Djibouti 
🇩🇰 flag: Denmark 
🇩🇲 flag: Dominica 
🇩🇴 flag: Dominican Republic 
🇩🇿 flag: Algeria 
🇪🇦 flag: Ceuta & Melilla 
🇪🇨 flag: Ecuador 
🇪🇪 flag: Estonia 
🇪🇬 flag: Egypt 
🇪🇭 flag: Western Sahara 
🇪🇷 flag: Eritrea 
🇪🇸 flag: Spain 
🇪🇹 flag: Ethiopia 
🇪🇺 flag: European Union 
🇫🇮 flag: Finland 
🇫🇯 flag: Fiji 
🇫🇰 flag: Falkland Islands 
🇫🇲 flag: Micronesia 
🇫🇴 flag: Faroe Islands 
🇫🇷 flag: France 
🇬🇦 flag: Gabon 
🇬🇧 flag: United Kingdom 
🇬🇩 flag: Grenada 
🇬🇪 flag: Georgia 
🇬🇫 flag: French Guiana 
🇬🇬 flag: Guernsey 
🇬🇭 flag: Ghana 
🇬🇮 flag: Gibraltar 
🇬🇱 flag: Greenland 
🇬🇲 flag: Gambia 
🇬🇳 flag: Guinea 
🇬🇵 flag: Guadeloupe 
🇬🇶 flag: Equatorial Guinea 
🇬🇷 flag: Greece 
🇬🇸 flag: South Georgia & South Sandwich Islands 
🇬🇹 flag: Guatemala 
🇬🇺 flag: Guam 
🇬🇼 flag: Guinea-Bissau 
🇬🇾 flag: Guyana 
🇭🇰 flag: Hong Kong SAR China 
🇭🇲 flag: Heard & McDonald Islands 
🇭🇳 flag: Honduras 
🇭🇷 flag: Croatia 
🇭🇹 flag: Haiti 
🇭🇺 flag: Hungary 
🇮🇨 flag: Canary Islands 
🇮🇩 flag: Indonesia 
🇮🇪 flag: Ireland 
🇮🇱 flag: Israel 
🇮🇲 flag: Isle of Man 
🇮🇳 flag: India 
🇮🇴 flag: British Indian Ocean Territory 
🇮🇶 flag: Iraq 
🇮🇷 flag: Iran 
🇮🇸 flag: Iceland 
🇮🇹 flag: Italy 
🇯🇪 flag: Jersey 
🇯🇲 flag: Jamaica 
🇯🇴 flag: Jordan 
🇯🇵 flag: Japan 
🇰🇪 flag: Kenya 
🇰🇬 flag: Kyrgyzstan 
🇰🇭 flag: Cambodia 
🇰🇮 flag: Kiribati 
🇰🇲 flag: Comoros 
🇰🇳 flag: St. Kitts & Nevis 
🇰🇵 flag: North Korea 
🇰🇷 flag: South Korea 
🇰🇼 flag: Kuwait 
🇰🇾 flag: Cayman Islands 
🇰🇿 flag: Kazakhstan 
🇱🇦 flag: Laos 
🇱🇧 flag: Lebanon 
🇱🇨 flag: St. Lucia 
🇱🇮 flag: Liechtenstein 
🇱🇰 flag: Sri Lanka 
🇱🇷 flag: Liberia 
🇱🇸 flag: Lesotho 
🇱🇹 flag: Lithuania 
🇱🇺 flag: Luxembourg 
🇱🇻 flag: Latvia 
🇱🇾 flag: Libya 
🇲🇦 flag: Morocco 
🇲🇨 flag: Monaco 
🇲🇩 flag: Moldova 
🇲🇪 flag: Montenegro 
🇲🇫 flag: St. Martin 
🇲🇬 flag: Madagascar 
🇲🇭 flag: Marshall Islands 
🇲🇰 flag: North Macedonia 
🇲🇱 flag: Mali 
🇲🇲 flag: Myanmar (Burma) 
🇲🇳 flag: Mongolia 
🇲🇴 flag: Macao SAR China 
🇲🇵 flag: Northern Mariana Islands 
🇲🇶 flag: Martinique 
🇲🇷 flag: Mauritania 
🇲🇸 flag: Montserrat 
🇲🇹 flag: Malta 
🇲🇺 flag: Mauritius 
🇲🇻 flag: Maldives 
🇲🇼 flag: Malawi 
🇲🇽 flag: Mexico 
🇲🇾 flag: Malaysia 
🇲🇿 flag: Mozambique 
🇳🇦 flag: Namibia 
🇳🇨 flag: New Caledonia 
🇳🇪 flag: Niger 
🇳🇫 flag: Norfolk Island 
🇳🇬 flag: Nigeria 
🇳🇮 flag: Nicaragua 
🇳🇱 flag: Netherlands 
🇳🇴 flag: Norway 
🇳🇵 flag: Nepal 
🇳🇷 flag: Nauru 
🇳🇺 flag: Niue 
🇳🇿 flag: New Zealand 
🇴🇲 flag: Oman 
🇵🇦 flag: Panama 
🇵🇪 flag: Peru 
🇵🇫 flag: French Polynesia 
🇵🇬 flag: Papua New Guinea 
🇵🇭 flag: Philippines 
🇵🇰 flag: Pakistan 
🇵🇱 flag: Poland 
🇵🇲 flag: St. Pierre & Miquelon 
🇵🇳 flag: Pitcairn Islands 
🇵🇷 flag: Puerto Rico 
🇵🇸 flag: Palestinian Territories 
🇵🇹 flag: Portugal 
🇵🇼 flag: Palau 
🇵🇾 flag: Paraguay 
🇶🇦 flag: Qatar 
🇷🇪 flag: Réunion 
🇷🇴 flag: Romania 
🇷🇸 flag: Serbia 
🇷🇺 flag: Russia 
🇷🇼 flag: Rwanda 
🇸🇦 flag: Saudi Arabia 
🇸🇧 flag: Solomon Islands 
🇸🇨 flag: Seychelles 
🇸🇩 flag: Sudan 
🇸🇪 flag: Sweden 
🇸🇬 flag: Singapore 
🇸🇭 flag: St. Helena 
🇸🇮 flag: Slovenia 
🇸🇯 flag: Svalbard & Jan Mayen 
🇸🇰 flag: Slovakia 
🇸🇱 flag: Sierra Leone 
🇸🇲 flag: San Marino 
🇸🇳 flag: Senegal 
🇸🇴 flag: Somalia 
🇸🇷 flag: Suriname 
🇸🇸 flag: South Sudan 
🇸🇹 flag: São Tomé & Príncipe 
🇸🇻 flag: El Salvador 
🇸🇽 flag: Sint Maarten 
🇸🇾 flag: Syria 
🇸🇿 flag: Eswatini 
🇹🇦 flag: Tristan da Cunha 
🇹🇨 flag: Turks & Caicos Islands 
🇹🇩 flag: Chad 
🇹🇫 flag: French Southern Territories 
🇹🇬 flag: Togo 
🇹🇭 flag: Thailand 
🇹🇯 flag: Tajikistan 
🇹🇰 flag: Tokelau 
🇹🇱 flag: Timor-Leste 
🇹🇲 flag: Turkmenistan 
🇹🇳 flag: Tunisia 
🇹🇴 flag: Tonga 
🇹🇷 flag: Turkey 
🇹🇹 flag: Trinidad & Tobago 
🇹🇻 flag: Tuvalu 
🇹🇼 flag: Taiwan 
🇹🇿 flag: Tanzania 
🇺🇦 flag: Ukraine 
🇺🇬 flag: Uganda 
🇺🇲 flag: U.S. Outlying Islands 
🇺🇳 flag: United Nations 
🇺🇸 flag: United States 
🇺🇾 flag: Uruguay 
🇺🇿 flag: Uzbekistan 
🇻🇦 flag: Vatican City 
🇻🇨 flag: St. Vincent & Grenadines 
🇻🇪 flag: Venezuela 
🇻🇬 flag: British Virgin Islands 
🇻🇮 flag: U.S. Virgin Islands 
🇻🇳 flag: Vietnam 
🇻🇺 flag: Vanuatu 
🇼🇫 flag: Wallis & Futuna 
🇼🇸 flag: Samoa 
🇽🇰 flag: Kosovo 
🇾🇪 flag: Yemen 
🇾🇹 flag: Mayotte 
🇿🇦 flag: South Africa 
🇿🇲 flag: Zambia 
🇿🇼 flag: Zimbabwe 
🏴󠁧󠁢󠁥󠁮󠁧󠁿 flag: England 
🏴󠁧󠁢󠁳󠁣󠁴󠁿 flag: Scotland 
🏴󠁧󠁢󠁷󠁬󠁳󠁿 flag: Wales 
"

echo "$emoji" | rofi -dmenu -i -multi-select -ballot-unselected-str " " -ballot-selected-str "x" | awk '{print $1}' | tr -d '\n' | xclip -sel c
