#!/bin/bash 

options="poweroff\nexit i3\nreboot"
response=$(echo -e "$options" | rofi -dmenu -p "Select an option"  )

case "$response" in
    "exit i3")
        i3-msg exit
        ;;
    "poweroff")
        sudo shutdown now
        ;;
    "reboot")
        reboot
        ;;
    "cancel")
        ;;
esac
