#!/usr/bin/bash 

options="⏻ poweroff\n reboot\n󰒲 suspend\n󰗽 logout\n󰷛 lock screen"
response=$(echo -e "$options" | rofi -theme-str 'window {width: 8%;}' -dmenu -p "("  )

case "$response" in
    "󰷛 lock screen")
        i3lock -c 002222
        ;;
    "󰗽 logout")
        i3-msg exit
        ;;
    "⏻ poweroff")
        sudo shutdown now
        ;;
    " reboot")
        reboot
        ;;
    "󰒲 suspend")
        systemctl suspend
        ;;
esac
