#!/usr/bin/bash 

options="lock i3\npoweroff\nexit i3\nsuspend\nreboot"
response=$(echo -e "$options" | rofi -dmenu -p "Select an option"  )

case "$response" in
    "lock i3")
        i3lock -c 000022
        ;;
    "exit i3")
        i3-msg exit
        ;;
    "poweroff")
        sudo shutdown now
        ;;
    "reboot")
        reboot
        ;;
    "suspend")
        systemctl suspend
        ;;
    "cancel")
        ;;
esac
