#!/usr/bin/bash

words="https://raw.githubusercontent.com/first20hours/google-10000-english/master/google-10000-english.txt"

generate_random_words() {
  curl $words | shuf
}

generate_random_base64_strings() {
  length=1024
  random_bytes=$(head -c $((length * 3 / 4)) /dev/urandom | base64)
  
  for ((i=4; i<=length; i+=4)); do
    echo "$((i/4)) $i ${random_bytes:0:i}"
  done
}

generate_random_hex_strings() {
  length=1024
  hex_string=$(hexdump -n $((length / 2)) -e '/1 "%02X"' /dev/urandom)

  for ((i=2; i<=length; i+=2)); do
    echo "$((i/4)) $i ${hex_string:0:i}"
  done
}

generate_random_strings() {
  for ((i=29; i>=0; i-=1)); do
    echo $i $(pwgen -syn1 $i)
  done
}

generate_random_passphrases() {
  wordlist=$(curl $words)
  for ((i=4; i<=10; i+=1)); do
    num_words=$i
    shuffled_words=$(shuf -e $wordlist)
    passphrase=$(echo "$shuffled_words" | head -n $i | tr '\n' ' ' | sed 's/.\{1\}$//')
    echo "$passphrase"
  done
}

generate_alphanumeric() {
  for ((i=4; i<=100; i+=1)); do
    echo -n "$i. "
    python3 -c "import random,string,sys; print(''.join(random.choices(string.ascii_lowercase + string.digits, k=int(sys.argv[1]) if len(sys.argv) > 1 else 4)))" $i
  done
}

menu_options=("random words\nrandom passphrases\nrandom base64 strings\nrandom hex strings\nrandom strings\nrandom alphanumeric")
selected_option=$(echo -e "${menu_options[@]}" | rofi -dmenu -p "choose an option")

case "$selected_option" in
  "random words")
    generate_random_words | rofi -dmenu -p "random words" | tr -d '\n' | xclip -sel c
    ;;
  "random passphrases")
    generate_random_passphrases | rofi -dmenu -p "random passphrases" | tr -d '\n' | xclip -sel c
    ;;
  "random base64 strings")
    generate_random_base64_strings | rofi -dmenu -p "random base64 strings" | awk '{print $NF}' | tr -d '\n'  | xclip -sel c
    ;;
  "random hex strings")
    generate_random_hex_strings | rofi -dmenu -p "random hex strings" | awk '{print $NF}' | tr -d '\n' | xclip -sel c
    ;;
  "random strings")
    generate_random_strings | rofi -dmenu -p "random strings" | awk '{print $NF}' | tr -d '\n' | xclip -sel c
    ;;
  "random alphanumeric")
    generate_alphanumeric | rofi -dmenu -p "random alphanumeric" | awk '{print $NF}' | tr -d '\n' | xclip -sel c
    ;;
esac
