#!/bin/bash

generate_random_words() {
  cat /usr/share/dict/words | shuf -n 1000
}

generate_random_base64_strings() {
  for ((i=3; i<=20*3; i+=3)); do
    head -c $i /dev/urandom | base64
  done
}

generate_random_hex_strings() {
  head -c "$1" /dev/urandom | hexdump -e '/1 "%02x"'
}

generate_random_numbers() {
  head -c "$1" /dev/urandom | tr -dc '0-9'
}

generate_random_strings() {
  head -c "$1" /dev/urandom | tr -dc '[:alnum:]'
}

generate_random_passphrases() {
  num_words=$1
  passphrase=$(generate_random_words "$num_words" | tr '\n' ' ')
  echo "$passphrase"
}

menu_options=("random words\nrandom base64 strings\nrandom hex strings\nrandom numbers\nrandom strings\nrandom passphrases")
selected_option=$(echo -e "${menu_options[@]}" | rofi -dmenu -p "choose an option")

case "$selected_option" in
  "random words")
    generate_random_words | rofi -dmenu -p "random words"
    ;;
  "random base64 strings")
    generate_random_base64_strings | rofi -dmenu -p "random base64 strings"
    ;;
  "random hex strings")
    generate_random_hex_strings | rofi -dmenu -p "random hex strings"
    ;;
  "random numbers")
    generate_random_numbers | rofi -dmenu -p "random numbers"
    ;;
  "random strings")
    generate_random_strings | rofi -dmenu -p "random strings"
    ;;
  "random passphrases")
    generate_random_passphrases | rofi -dmenu -p "random passphrases"
    ;;
esac
