#!/usr/bin/bash

nmcli connection show --active | sed 1d | awk -F' {2,}' '{print $1}' | while read -r connection; do nmcli connection down "$connection"; done

nmcli connection up "$(nmcli connection show | sed 1d | rofi -dmenu | awk -F' {2,}' '{print $1}')"
