#!/usr/bin/bash 

links=$(cat <<EOF
󰇥 duckduckgo ai @ https://duckduckgo.com/?t=h_&q=-&ia=chat
󰚩 chatgpt @ https://chat.openai.com/chat/
 bing ai @ https://www.bing.com/chat?q=Microsoft+Copilot&FORM=hpcodx
󰊫 gmail @ https://gmail.com/
󰗃 youtube @ https://www.youtube.com/
 twitter @ https://twitter.com/
 twitch @ https://www.twitch.tv/
 instagram @ https://www.instagram.com/
 reddit @ https://www.reddit.com/
 pinterest @ https://www.pinterest.com/
󰫑 mastodon @ mastodon.social/
 hackernews @ https://news.ycombinator.com/active
󰖬 wikipedia @ https://en.wikipedia.org/
 github @ https://github.com/clydeconfigs/
 amazon @ amazon.es
 ebay @ https://www.ebay.es
 gnu manuals @ https://www.gnu.org/manual/manual.html
 arch linux @ https://bbs.archlinux.org/search.php?action=show_replies
󰟞 123movies @ https://ww2.123moviesfree.net/
EOF
)

link=$(echo "$links" | sed 's/ @.*//' | rofi -dmenu -theme-str 'window {width: 20%;}' )

test -n $link || firefox $(sed -n 's/'"$link"' @ //p' <<< "$links")
