#!/usr/bin/bash 

links="$(cat $HOME/media/code/share/weblinks)"

link=$(echo "$links" | sed 's/ @.*//' | rofi -dmenu -theme-str 'window {width: 20%;}' )

test -n "$link" && firefox "$(sed -n 's/'"$link"' @ //p' <<< "$links")"
